version: "3"
services:
    xotomicro-front-auth-service:
        build:
            context: ./
            dockerfile: docker/dockerfile.production
            args:
                - GITHUB_TOKEN=${GITHUB_TOKEN}
        container_name: xotomicro-front-auth-service
        ports:
            - 7075:80
