version: "3"
services:
  xotomicro-front-auth-service:
    build:
      context: ./
      dockerfile: docker/dockerfile.development
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: xotomicro-front-auth-service
    ports:
      - 7075:7075
    volumes:
      - ./:/app
