apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-front-auth-service
  name: xotomicro-front-auth-service
spec:
  ports:
    - name: "7075"
      port: 7075
      targetPort: 80
  selector:
    io.kompose.service: xotomicro-front-auth-service
status:
  loadBalancer: {}
